In [11]:
import json
import numpy as np

# anno = json.load(open('data/Thumos14/Thumos14_annotations.json'))
anno = json.load(open('data/ActivityNet13/ActivityNet13_annotations.json'))
video_anno = anno['database']
list_duration = []
list_seg = []
count = 0
for vn, annos in video_anno.items():
    if annos['subset'] == "val":
        list_duration.append(annos['duration'])
        for seg in annos['annotations']:
            time = seg['segment'][1]-seg['segment'][0]
            list_seg.append(time)
        count = count + 1

x = np.sort(list_seg)
y = np.sort(list_duration)
print(x)
print(y)
print(sum(y)/count)

[  0.           0.           0.         ... 266.971      277.76528327
 300.31687075]
[  1.10205717   2.06666667   2.33566667 ... 360.36       619.26666667
 745.44      ]
117.70481736230505


In [36]:
import torch
import math

feature_length = 20
window_size = 5
slice_overlap = 0.75
slide = window_size*(1-slice_overlap)
num_complete_slices = math.floor((feature_length-window_size)/slide) + 1
print(num_complete_slices)
slices = [[int(i*slide), int((i*slide)+window_size-1)] for i in range(num_complete_slices)]

print(slices)

13
[[0, 4], [1, 5], [2, 6], [3, 7], [5, 9], [6, 10], [7, 11], [8, 12], [10, 14], [11, 15], [12, 16], [13, 17], [15, 19]]


In [57]:
import json

res = json.load(open("C:/Users/adminA/Desktop/detection_val_10_raw.json"))
video_id = "-Jp86pFKlsw"
print(len(res['results'][video_id]))
sorted_res = sorted(res['results'][video_id],key=lambda proposal: proposal['score'],reverse=True)
sorted_res

5


[{'segment': [4.131891250610352, 24.000808715820312],
  'label': 'foreground',
  'score': 0.617004930973053},
 {'segment': [8.320490837097168, 19.924226760864258],
  'label': 'foreground',
  'score': 0.2743481695652008},
 {'segment': [15.117510795593262, 26.317546844482422],
  'label': 'foreground',
  'score': 0.2682434618473053},
 {'segment': [3.746934175491333, 9.808257102966309],
  'label': 'foreground',
  'score': 0.2471596896648407},
 {'segment': [0.6245707273483276, 2.9960780143737793],
  'label': 'foreground',
  'score': 0.20803634822368622}]

In [34]:
import numpy as np
input_dets = np.random.random((5,4))
print(input_dets)
sort_idx = input_dets[:, 2].argsort()[::-1]
dets = input_dets[sort_idx, :]
print(dets)
np.where(dets[:,2]<=0.01)[0]

[[0.71611393 0.96510105 0.71217216 0.18761535]
 [0.13681803 0.81023881 0.8162105  0.48607804]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]
[[0.13681803 0.81023881 0.8162105  0.48607804]
 [0.71611393 0.96510105 0.71217216 0.18761535]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]


array([], dtype=int64)

In [10]:
# check_repeat video file

video_name = list()
# /mnt/Datasets/COIN/videos/0/-8NaVGEccgc.mp4
with open("C:/Users/14988/Desktop/HACS_video_dir_list.txt") as f:
    for line in f.readlines():
        vn = line.strip().split('/')[-1]
        video_name.append(vn)
print(len(video_name))

visited = set()
redundant_items = [x for x in video_name if x in visited or (visited.add(x) or False)]
print(redundant_items)

# print(video_name)


5641
['v_GkDRj1GlHig.mp4', 'v_Qe-tz6I222M.mp4', 'v_4n8zXCsLycU.mp4', 'v_oDyKqL-bnVw.mp4']


In [85]:
import torch

# 假设你有一个名为tensor的布尔张量
tensor = torch.tensor([True, True, False, False, False, True, True, True])

# 找到False值的开始和结束索引
false_indices = torch.where(tensor == False)[0]
start_index = false_indices[0]
end_index = false_indices[-1]

print("False values start at index:", start_index.item())
print("False values end at index:", end_index.item())

False values start at index: 2
False values end at index: 4


In [3]:
import torch
import torch.nn as nn

def inverse_sigmoid(x, eps=1e-5):
    x = x.clamp(min=0, max=1)
    x1 = x.clamp(min=eps)
    x2 = (1 - x).clamp(min=eps)
    return torch.log(x1/x2)


num_queries = 3
feat = torch.empty((6,4)).uniform_(0,1)
print(feat)
idx = torch.tensor([0,1,2])
a = feat[idx,:]
print(a)

tensor([[0.3682, 0.8972, 0.3394, 0.3260],
        [0.1439, 0.8706, 0.7251, 0.2740],
        [0.7318, 0.2247, 0.8523, 0.5513],
        [0.4105, 0.7412, 0.4069, 0.6733],
        [0.4753, 0.3614, 0.4514, 0.3871],
        [0.3681, 0.5327, 0.9832, 0.0176]])
tensor([[0.3682, 0.8972, 0.3394, 0.3260],
        [0.1439, 0.8706, 0.7251, 0.2740],
        [0.7318, 0.2247, 0.8523, 0.5513]])


In [52]:
import torch
import numpy as np

a = np.array([[1,2,3],[2,3,4]])
b = ((a[:, :0] >= 15).sum(axis=1)> 0).sum()
print(b)

0
