In [11]:
import json
import numpy as np

# anno = json.load(open('data/Thumos14/Thumos14_annotations.json'))
anno = json.load(open('data/ActivityNet13/ActivityNet13_annotations.json'))
video_anno = anno['database']
list_duration = []
list_seg = []
count = 0
for vn, annos in video_anno.items():
    if annos['subset'] == "val":
        list_duration.append(annos['duration'])
        for seg in annos['annotations']:
            time = seg['segment'][1]-seg['segment'][0]
            list_seg.append(time)
        count = count + 1

x = np.sort(list_seg)
y = np.sort(list_duration)
print(x)
print(y)
print(sum(y)/count)

[  0.           0.           0.         ... 266.971      277.76528327
 300.31687075]
[  1.10205717   2.06666667   2.33566667 ... 360.36       619.26666667
 745.44      ]
117.70481736230505


In [36]:
import torch
import math

feature_length = 20
window_size = 5
slice_overlap = 0.75
slide = window_size*(1-slice_overlap)
num_complete_slices = math.floor((feature_length-window_size)/slide) + 1
print(num_complete_slices)
slices = [[int(i*slide), int((i*slide)+window_size-1)] for i in range(num_complete_slices)]

print(slices)

13
[[0, 4], [1, 5], [2, 6], [3, 7], [5, 9], [6, 10], [7, 11], [8, 12], [10, 14], [11, 15], [12, 16], [13, 17], [15, 19]]


In [5]:
import json

res = json.load(open("C:/Users/adminA/Desktop/detection_val_67_raw.json"))
video_id = "2imjxY43yYM"
print(len(res['results'][video_id]))
sorted_res = sorted(res['results'][video_id],key=lambda proposal: proposal['score'],reverse=True)
sorted_res

100


[{'segment': [22.694108963012695, 92.5130615234375],
  'label': 'Removing curlers',
  'score': 0.388469934463501},
 {'segment': [16.63426399230957, 44.200355529785156],
  'label': 'Removing curlers',
  'score': 0.319789856672287},
 {'segment': [96.78557586669922, 157.68389892578125],
  'label': 'Removing curlers',
  'score': 0.31710901856422424},
 {'segment': [1.5644112825393677, 187.9210662841797],
  'label': 'Removing curlers',
  'score': 0.3028223216533661},
 {'segment': [1.5644112825393677, 187.9210662841797],
  'label': 'Zumba',
  'score': 0.24550430476665497},
 {'segment': [96.78557586669922, 157.68389892578125],
  'label': 'Shot put',
  'score': 0.1875888705253601},
 {'segment': [136.07127380371094, 171.49365234375],
  'label': 'Shot put',
  'score': 0.1686376929283142},
 {'segment': [22.694108963012695, 92.5130615234375],
  'label': 'Shot put',
  'score': 0.15017662942409515},
 {'segment': [136.07127380371094, 171.49365234375],
  'label': 'Removing curlers',
  'score': 0.143508

In [34]:
import numpy as np
input_dets = np.random.random((5,4))
print(input_dets)
sort_idx = input_dets[:, 2].argsort()[::-1]
dets = input_dets[sort_idx, :]
print(dets)
np.where(dets[:,2]<=0.01)[0]

[[0.71611393 0.96510105 0.71217216 0.18761535]
 [0.13681803 0.81023881 0.8162105  0.48607804]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]
[[0.13681803 0.81023881 0.8162105  0.48607804]
 [0.71611393 0.96510105 0.71217216 0.18761535]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]


array([], dtype=int64)

In [10]:
# check_repeat video file

video_name = list()
# /mnt/Datasets/COIN/videos/0/-8NaVGEccgc.mp4
with open("C:/Users/14988/Desktop/HACS_video_dir_list.txt") as f:
    for line in f.readlines():
        vn = line.strip().split('/')[-1]
        video_name.append(vn)
print(len(video_name))

visited = set()
redundant_items = [x for x in video_name if x in visited or (visited.add(x) or False)]
print(redundant_items)

# print(video_name)


5641
['v_GkDRj1GlHig.mp4', 'v_Qe-tz6I222M.mp4', 'v_4n8zXCsLycU.mp4', 'v_oDyKqL-bnVw.mp4']


In [17]:
import torch
a = torch.randn((3,4,5))
idx = ([0,1],[2,3])
print(a)
print(a[idx])

tensor([[[ 1.1455e+00, -1.6325e+00, -2.4235e+00,  9.5787e-03,  1.5145e+00],
         [-1.0254e+00,  6.5051e-01, -6.4121e-01, -3.8108e-01,  5.1454e-01],
         [ 9.3568e-01,  2.5152e+00,  1.1037e-01, -1.1426e+00, -8.9377e-01],
         [-7.5443e-01,  9.0965e-01,  5.4615e-01, -6.1372e-01,  1.1822e+00]],

        [[ 5.3479e-01,  7.9926e-01, -1.6796e+00,  2.1524e-01,  1.3877e+00],
         [ 1.1227e+00,  6.0966e-02,  2.3339e-01, -5.7269e-01, -4.1698e-01],
         [ 2.2959e-01, -9.9631e-01, -1.0721e+00, -3.6477e-01, -1.6207e+00],
         [-7.3623e-01, -4.5509e-01, -9.7884e-01, -1.4972e-01, -7.1234e-01]],

        [[-1.2021e+00,  1.5812e-01,  2.1838e-03, -3.4663e-01, -4.5690e-01],
         [ 6.5222e-01,  5.9593e-01, -1.8110e-03, -6.8901e-01,  6.6121e-01],
         [ 1.5501e+00, -1.7826e-01, -9.8826e-01, -6.3940e-01, -1.9090e-01],
         [ 6.6442e-01,  1.0397e+00, -1.0567e+00, -9.7999e-01, -1.2419e+00]]])
tensor([[ 0.9357,  2.5152,  0.1104, -1.1426, -0.8938],
        [-0.7362, -0.4551, 

In [3]:
import torch
import torch.nn as nn

def inverse_sigmoid(x, eps=1e-5):
    x = x.clamp(min=0, max=1)
    x1 = x.clamp(min=eps)
    x2 = (1 - x).clamp(min=eps)
    return torch.log(x1/x2)


num_queries = 3
feat = torch.empty((6,4)).uniform_(0,1)
print(feat)
idx = torch.tensor([0,1,2])
a = feat[idx,:]
print(a)

tensor([[0.3682, 0.8972, 0.3394, 0.3260],
        [0.1439, 0.8706, 0.7251, 0.2740],
        [0.7318, 0.2247, 0.8523, 0.5513],
        [0.4105, 0.7412, 0.4069, 0.6733],
        [0.4753, 0.3614, 0.4514, 0.3871],
        [0.3681, 0.5327, 0.9832, 0.0176]])
tensor([[0.3682, 0.8972, 0.3394, 0.3260],
        [0.1439, 0.8706, 0.7251, 0.2740],
        [0.7318, 0.2247, 0.8523, 0.5513]])


In [9]:
import torch

a = torch.randn((3,4,5))
a_prob = a.softmax(-1)
print(a_prob)
a_cls = a.argmax(-1)
print(a_cls)

b = torch.randn((5,3))
print(b)
b_cls = b[a_cls]
print(b_cls)

tensor([[[0.0393, 0.0465, 0.2687, 0.4451, 0.2004],
         [0.3336, 0.1316, 0.0256, 0.0771, 0.4320],
         [0.1303, 0.2095, 0.0244, 0.5300, 0.1059],
         [0.6344, 0.0201, 0.2756, 0.0283, 0.0416]],

        [[0.4607, 0.0363, 0.0981, 0.0477, 0.3572],
         [0.0878, 0.1337, 0.3883, 0.1242, 0.2661],
         [0.3205, 0.2010, 0.0647, 0.1810, 0.2328],
         [0.2512, 0.2952, 0.2662, 0.0871, 0.1002]],

        [[0.1198, 0.0721, 0.0557, 0.3896, 0.3629],
         [0.6438, 0.0438, 0.0234, 0.2140, 0.0750],
         [0.6450, 0.0380, 0.0219, 0.2491, 0.0460],
         [0.1833, 0.2324, 0.0378, 0.1576, 0.3889]]])
tensor([[3, 4, 3, 0],
        [0, 2, 0, 1],
        [3, 0, 0, 4]])
tensor([[-0.3957,  0.4386,  0.5107],
        [ 2.4397, -0.2881, -1.0476],
        [-0.1288,  2.3236,  0.0763],
        [ 0.1350,  0.5698,  0.1841],
        [-0.0105, -0.4896,  0.9327]])
tensor([[[ 0.1350,  0.5698,  0.1841],
         [-0.0105, -0.4896,  0.9327],
         [ 0.1350,  0.5698,  0.1841],
         [-0.39