In [11]:
import json
import numpy as np

# anno = json.load(open('data/Thumos14/Thumos14_annotations.json'))
anno = json.load(open('data/ActivityNet13/ActivityNet13_annotations.json'))
video_anno = anno['database']
list_duration = []
list_seg = []
count = 0
for vn, annos in video_anno.items():
    if annos['subset'] == "val":
        list_duration.append(annos['duration'])
        for seg in annos['annotations']:
            time = seg['segment'][1]-seg['segment'][0]
            list_seg.append(time)
        count = count + 1

x = np.sort(list_seg)
y = np.sort(list_duration)
print(x)
print(y)
print(sum(y)/count)

[  0.           0.           0.         ... 266.971      277.76528327
 300.31687075]
[  1.10205717   2.06666667   2.33566667 ... 360.36       619.26666667
 745.44      ]
117.70481736230505


In [36]:
import torch
import math

feature_length = 20
window_size = 5
slice_overlap = 0.75
slide = window_size*(1-slice_overlap)
num_complete_slices = math.floor((feature_length-window_size)/slide) + 1
print(num_complete_slices)
slices = [[int(i*slide), int((i*slide)+window_size-1)] for i in range(num_complete_slices)]

print(slices)

13
[[0, 4], [1, 5], [2, 6], [3, 7], [5, 9], [6, 10], [7, 11], [8, 12], [10, 14], [11, 15], [12, 16], [13, 17], [15, 19]]


## Load the result on ActivityNet1.3

In [ ]:
import json

# res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/activitynet1.3/v8_49_detection_val_93_raw.json")) # base
# res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/activitynet1.3/v8_3_detection_val_66_raw.json")) # + actionness
# res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/activitynet1.3/v8_11_detection_val_23_raw.json"))  # + refine
res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/activitynet1.3/v8_38_detection_val_47_raw.json"))   # + actionness + refine
video_id = "-r_bvqjYjYg"
print(len(res['results'][video_id]))
sorted_res = sorted(res['results'][video_id],key=lambda proposal: proposal['score'],reverse=True)
sorted_res

## Load the result on Thumos14
- 注意在Thumos14的detection_val文件是来自binary的预测

In [94]:
import json

res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/thumos14/v8_1_2_detection_test_20_raw.json")) # base
# res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/thumos14/v8_3_2_detection_test_27_raw.json")) # + actionness
# res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/thumos14/v8_2_detection_test_28_raw.json"))  # + refine
# res = json.load(open("D:/Jia-Run/Zero_Shot_TAL/论文写作/画图/ablation/thumos14/v8_4_detection_test_47_raw.json"))   # + actionness + refine
video_id = "video_test_0000073"
print(len(res['results'][video_id]))
sorted_res = sorted(res['results'][video_id],key=lambda proposal: proposal['score'],reverse=True)
sorted_res

70


[{'segment': [49.64062843322754, 53.64390335083008],
  'label': 'foreground',
  'score': 0.6140000820159912},
 {'segment': [5.714236259460449, 10.004910469055176],
  'label': 'foreground',
  'score': 0.5571966767311096},
 {'segment': [38.28494129180908, 43.53189239501953],
  'label': 'foreground',
  'score': 0.39096713066101074},
 {'segment': [94.15474967956543, 97.93608169555664],
  'label': 'foreground',
  'score': 0.3716582953929901},
 {'segment': [18.688444137573242, 22.87190055847168],
  'label': 'foreground',
  'score': 0.3694264888763428},
 {'segment': [94.27256088256836, 98.06117897033691],
  'label': 'foreground',
  'score': 0.35019028186798096},
 {'segment': [94.06323890686035, 97.73961334228515],
  'label': 'foreground',
  'score': 0.33394965529441833},
 {'segment': [88.9366720199585, 93.23164443969726],
  'label': 'foreground',
  'score': 0.3249224126338959},
 {'segment': [94.78466873168945, 98.30124359130859],
  'label': 'foreground',
  'score': 0.20245936512947083},
 {'se

In [34]:
import numpy as np
input_dets = np.random.random((5,4))
print(input_dets)
sort_idx = input_dets[:, 2].argsort()[::-1]
dets = input_dets[sort_idx, :]
print(dets)
np.where(dets[:,2]<=0.01)[0]

[[0.71611393 0.96510105 0.71217216 0.18761535]
 [0.13681803 0.81023881 0.8162105  0.48607804]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]
[[0.13681803 0.81023881 0.8162105  0.48607804]
 [0.71611393 0.96510105 0.71217216 0.18761535]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]


array([], dtype=int64)

In [10]:
# check_repeat video file

video_name = list()
# /mnt/Datasets/COIN/videos/0/-8NaVGEccgc.mp4
with open("C:/Users/14988/Desktop/HACS_video_dir_list.txt") as f:
    for line in f.readlines():
        vn = line.strip().split('/')[-1]
        video_name.append(vn)
print(len(video_name))

visited = set()
redundant_items = [x for x in video_name if x in visited or (visited.add(x) or False)]
print(redundant_items)

# print(video_name)


5641
['v_GkDRj1GlHig.mp4', 'v_Qe-tz6I222M.mp4', 'v_4n8zXCsLycU.mp4', 'v_oDyKqL-bnVw.mp4']


In [3]:
import torch
import torch.nn as nn

def inverse_sigmoid(x, eps=1e-5):
    x = x.clamp(min=0, max=1)
    x1 = x.clamp(min=eps)
    x2 = (1 - x).clamp(min=eps)
    return torch.log(x1/x2)


num_queries = 3
feat = torch.empty((6,4)).uniform_(0,1)
print(feat)
idx = torch.tensor([0,1,2])
a = feat[idx,:]
print(a)

tensor([[0.3682, 0.8972, 0.3394, 0.3260],
        [0.1439, 0.8706, 0.7251, 0.2740],
        [0.7318, 0.2247, 0.8523, 0.5513],
        [0.4105, 0.7412, 0.4069, 0.6733],
        [0.4753, 0.3614, 0.4514, 0.3871],
        [0.3681, 0.5327, 0.9832, 0.0176]])
tensor([[0.3682, 0.8972, 0.3394, 0.3260],
        [0.1439, 0.8706, 0.7251, 0.2740],
        [0.7318, 0.2247, 0.8523, 0.5513]])


In [67]:
import torch
import numpy as np

np.linspace(0.5, 0.95, 10)

array([0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])