In [11]:
import json
import numpy as np

# anno = json.load(open('data/Thumos14/Thumos14_annotations.json'))
anno = json.load(open('data/ActivityNet13/ActivityNet13_annotations.json'))
video_anno = anno['database']
list_duration = []
list_seg = []
count = 0
for vn, annos in video_anno.items():
    if annos['subset'] == "val":
        list_duration.append(annos['duration'])
        for seg in annos['annotations']:
            time = seg['segment'][1]-seg['segment'][0]
            list_seg.append(time)
        count = count + 1

x = np.sort(list_seg)
y = np.sort(list_duration)
print(x)
print(y)
print(sum(y)/count)

[  0.           0.           0.         ... 266.971      277.76528327
 300.31687075]
[  1.10205717   2.06666667   2.33566667 ... 360.36       619.26666667
 745.44      ]
117.70481736230505


In [36]:
import torch
import math

feature_length = 20
window_size = 5
slice_overlap = 0.75
slide = window_size*(1-slice_overlap)
num_complete_slices = math.floor((feature_length-window_size)/slide) + 1
print(num_complete_slices)
slices = [[int(i*slide), int((i*slide)+window_size-1)] for i in range(num_complete_slices)]

print(slices)

13
[[0, 4], [1, 5], [2, 6], [3, 7], [5, 9], [6, 10], [7, 11], [8, 12], [10, 14], [11, 15], [12, 16], [13, 17], [15, 19]]


In [35]:
import json

res = json.load(open("C:/Users/14988/Desktop/detection_test_51_raw.json"))
video_id = "video_test_0000839"
print(len(res['results'][video_id]))
sorted_res = sorted(res['results'][video_id],key=lambda proposal: proposal['score'],reverse=True)
sorted_res

92


[{'segment': [27.093441009521484, 30.813663482666016],
  'label': 'foreground',
  'score': 0.8585342764854431},
 {'segment': [68.55260963439942, 74.15573997497559],
  'label': 'foreground',
  'score': 0.8562423586845398},
 {'segment': [250.25214042663575, 256.6426128387451],
  'label': 'foreground',
  'score': 0.7962952256202698},
 {'segment': [83.08966760635376, 87.58659915924072],
  'label': 'foreground',
  'score': 0.794497549533844},
 {'segment': [42.196702575683595, 47.588433837890626],
  'label': 'foreground',
  'score': 0.7896634340286255},
 {'segment': [183.70449657440184, 191.4683982849121],
  'label': 'foreground',
  'score': 0.7444487810134888},
 {'segment': [320.6153709411621, 325.81831855773925],
  'label': 'foreground',
  'score': 0.737180769443512},
 {'segment': [210.70351343154908, 216.6733596801758],
  'label': 'foreground',
  'score': 0.6864185333251953},
 {'segment': [156.8911124229431, 162.10001049041747],
  'label': 'foreground',
  'score': 0.6716388463973999},
 {'

In [34]:
import numpy as np
input_dets = np.random.random((5,4))
print(input_dets)
sort_idx = input_dets[:, 2].argsort()[::-1]
dets = input_dets[sort_idx, :]
print(dets)
np.where(dets[:,2]<=0.01)[0]

[[0.71611393 0.96510105 0.71217216 0.18761535]
 [0.13681803 0.81023881 0.8162105  0.48607804]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]
[[0.13681803 0.81023881 0.8162105  0.48607804]
 [0.71611393 0.96510105 0.71217216 0.18761535]
 [0.24997616 0.52386834 0.37161187 0.65872146]
 [0.71864529 0.42397581 0.22944962 0.90087491]
 [0.47526494 0.06547175 0.0770536  0.09212093]]


array([], dtype=int64)